language: haxe
sudo: true
git:
  depth: 3

notifications:
  email:
    on_success: always
    on_failure: always

env:
  - CXX=g++-4.8

before_install: 
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-4.8 libxtst-dev libpng++-dev -y -q
  - nvm install node
  #- sudo npm install -g node-gyp

install:

  # Install Haxelib libs
  - yes | haxelib install build.hxml
  - yes | haxelib install build-test-simple.hxml
 
  # Install for simple test 
  - cd test/simple
  - npm install
  - cd ../..

before_script:

  # Need GUI (TODO - only do this for Linux)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:

  # Build lib
  - haxe build.hxml

  # Build simple test
  - haxe build-test-simple.hxml

  # Run simple test
  - cd test/simple
  - nvm run node test.js
  