language: haxe
sudo: false

install:
  - yes | haxelib install build.hxml
  - yes | haxelib install test/simple/build-test-simple.hxml

script:
  - haxe build.hxml
  - cd test/simple
  - haxe build-test-simple.hxml
