language: haxe
sudo: true
git:
  depth: 3

env:
  - CXX=g++-4.8

before_install: 
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-4.8 libxtst-dev libpng++-dev -y
  - nvm install node
  #- sudo npm install -g node-gyp

install:

  # Install Haxelib libs
  - yes | haxelib install build.hxml
  - yes | haxelib install test/simple/build-test-simple.hxml
 
  # Install for simple test 
  - cd test/simple
  - npm install
  - cd ../..

script:

  # Build lib
  - haxe build.hxml

  # Build simple test
  - cd test/simple
  - haxe build-test-simple.hxml

  # Run simple test
  - nvm run node test.js
  