language: haxe
sudo: true
git:
  depth: 3

env:
  - CXX=g++-4.6

before_install: 
  - sudo apt-get update
  - sudo apt-get install g++-4.6 libxtst-dev libpng++-dev 
  - nvm install node
  #- sudo npm install -g node-gyp

install:

  # Install Haxelib libs
  - yes | haxelib install build.hxml
  - yes | haxelib install test/simple/build-test-simple.hxml
 
  # Install for simple test 
  - cd test/simple
  - npm install
  - cd ../..

script:

  # Build lib
  - haxe build.hxml

  # Build simple test
  - cd test/simple
  - haxe build-test-simple.hxml

  # Run simple test
  - nvm run node test.js
  